apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http-8080 
      port: 8080
      targetPort: 8080
    - name: http-8081
      port: 8081
      targetPort: 8081
    - name: http-8082 
      port: 8082
      targetPort: 8082
  type: ClusterIP
